import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
function page(values={}) {
  const elements=new Map();
  function el(tag='div'){return {tag,children:[],textContent:'',value:'',checked:false,hidden:false,dataset:{},listeners:{},appendChild(n){this.children.push(n);return n;},replaceChildren(...ns){this.children=ns;},setAttribute(){},addEventListener(t,f){this.listeners[t]=f;},focus(){},emit(t){return this.listeners[t]?.({preventDefault(){}});}};}
  const document={getElementById(id){if(!elements.has(id))elements.set(id,el());return elements.get(id);},createElement:el};
  const state={data:{days:[],settings:{goalWeightLb:null,sleepTargetMinutes:480,wakeMinute:420,bedtimeBufferMinutes:30,habitLabel:'Late caffeine'}},status:'local',error:'',lastSync:null};
  const calls=[];let notify;
  const store={snapshot:()=>state,subscribe:f=>{notify=f;},saveDay:r=>{calls.push(['day',r]);},saveSettings:s=>{calls.push(['settings',s]);},removeDay:d=>{calls.push(['delete',d]);},sync:async()=>{calls.push(['sync']);}};
  let captured;
  const ctx=vm.createContext({Date,Number,String,Math,JSON,Promise,Error,ScratchMetrics:{localDate:()=> '2026-09-21'},ScratchAnalytics:{summary:input=>{captured=input;return Object.fromEntries(['weight','sleep','restingHeartRate','strength','adherence','effort','associations','nutrition'].map(k=>[k,{status:'insufficient',reason:'More recorded days needed',values:values[k]||{},samples:0}]));}}});
  vm.runInContext(fs.readFileSync(new URL('../analytics-view.js',import.meta.url),'utf8'),ctx,{filename:fileURLToPath(new URL('../analytics-view.js',import.meta.url))});
  const api=ctx.ScratchAnalyticsView.init({document,store,getWeights:()=>({records:[]}),getHealth:()=>({days:[]}),getEntries:()=>[]});
  return {api,state,calls,store,notify:()=>notify(),captured:()=>captured,$:id=>document.getElementById(id)};
}
function text(n){return n.textContent+' '+n.children.map(text).join(' ');}
test('empty analytics are honest and optional forms start blank',()=>{const p=page();assert.match(text(p.$('analytics-results')),/More recorded days/);assert.equal(p.$('journal-calories').value,'');assert.equal(p.$('analytics-goal').value,'');assert.equal(p.$('journal-date').value,'2026-09-21');});
test('journal passes blanks as null and known absence separately, then syncs',async()=>{const p=page();p.$('journal-calories').value='2200';p.$('journal-habit').value='no';p.$('journal-habit').emit('change');await p.$('journal-form').emit('submit');const row=p.calls[0][1];assert.equal(row.caloriesKcal,2200);assert.equal(row.effort,null);assert.equal(row.habit,false);assert.equal(p.calls[1][0],'sync');});
test('failed save retains user entry and reports error',async()=>{const p=page();p.store.saveDay=()=>{throw Error('Storage full');};p.$('journal-calories').value='2200';await p.$('journal-form').emit('submit');assert.equal(p.$('journal-calories').value,'2200');assert.match(p.$('analytics-message').textContent,/Storage full/);assert.equal(p.calls.length,0);});
test('settings store explicit sleep minutes and clock minute; refresh preserves draft',async()=>{const p=page();p.$('analytics-goal').value='180';p.$('analytics-sleep').value='8.5';p.$('analytics-wake').value='07:30';p.api.refresh();assert.equal(p.$('analytics-goal').value,'180');await p.$('analytics-settings').emit('submit');const s=p.calls[0][1];assert.equal(s.goalWeightLb,180);assert.equal(s.sleepTargetMinutes,510);assert.equal(s.wakeMinute,450);});
test('deletion requires explicit confirm; selecting day fills correction fields',async()=>{const p=page();p.state.data.days=[{date:'2026-09-20',caloriesKcal:2100,effort:5,sessionMinutes:30,restDay:false,habit:true,energy:7,deleted:false}];p.$('journal-date').value='2026-09-20';p.$('journal-date').emit('change');assert.equal(p.$('journal-calories').value,'2100');p.$('journal-delete').emit('click');assert.equal(p.calls.length,0);await p.$('journal-delete-confirm').emit('click');assert.equal(p.calls[0][0],'delete');assert.equal(p.calls[0][1],'2026-09-20');});
test('status and summary use independent journal source; sync errors remain visible',()=>{const p=page();p.state.status='error';p.state.error='GitHub unavailable';p.notify();assert.match(p.$('analytics-status').textContent,/GitHub unavailable/);assert.equal(p.captured().journal,p.state.data);});

test('dirty habit answer retains the label the user actually saw across remote changes',async()=>{const p=page();p.$('journal-habit').value='yes';p.$('journal-habit').emit('change');p.state.data.settings.habitLabel='Evening walk';p.notify();assert.match(p.$('journal-habit-label').textContent,/Late caffeine/);await p.$('journal-form').emit('submit');assert.equal(p.calls[0][1].habitLabel,'Late caffeine');assert.equal(p.calls[0][1].habit,true);});

test('editing calories does not overwrite an older habit answer',async()=>{const p=page();p.state.data.days=[{date:'2026-09-21',caloriesKcal:2000,habit:true,habitLabel:'Evening walk'}];p.notify();assert.equal(p.$('journal-habit').value,'');assert.match(p.$('journal-habit-note').textContent,/Evening walk/);p.$('journal-calories').value='2100';await p.$('journal-form').emit('submit');assert.equal(Object.hasOwn(p.calls[0][1],'habit'),false);assert.equal(Object.hasOwn(p.calls[0][1],'habitLabel'),false);});

test('populated calculation contract renders numbers, histories and uncertainty',()=>{const p=page({weight:{weeklyLb:-1,weeklyPercent:-0.5,trendLb:198,plateau:false,goalDate:'2027-01-01',spanDays:28,asOfDate:'2026-09-21',slopeInterval:[-1.2,-0.8]},sleep:{shortfall7Minutes:120,observed7:7,shortfall14Minutes:240,observed14:14,regularityMinutes:12,bedtimeMinute:1350},restingHeartRate:{currentBpm:61,baselineBpm:58,deviationBpm:3},strength:{records:[{setup:'Leg press',loadLb:100}],weeklySets:[{muscle:'quadriceps',sets:3}],weeklyExerciseSets:[{exerciseId:'leg-press',sets:3}],volume:[{date:'2026-09-21',setup:'Leg press',loadReps:2400,unit:'lb·reps'}],estimatedMaxes:[{setup:'Leg press',estimatedLb:120}],estimatedHistory:[{date:'2026-09-21',setup:'Leg press',estimatedLb:120}]},adherence:{percent:100,completedSets:3,plannedSets:3,extraSets:0},effort:{load7:130,load42:75,balance:-45,days:42,history:[{date:'2026-09-21',load:150,source:'manual'}]},associations:{habitLabel:'Late caffeine',taggedN:10,untaggedN:10,nextSleepDifferenceMinutes:-15},nutrition:{estimatedKcal:2400,meanIntakeKcal:2200,windowDays:28,sensitivityKcal:[2300,2500]}});const s=text(p.$('analytics-results'));for(const v of ['2,400 lb·reps','120 lb','Daily effort history','150','manual','Estimated strength history','130 units','not a confidence interval','-1.2 to -0.8'])assert.ok(s.includes(v),v);});
